package disher

var DefaultDishes = map[string]string{
	"pizza-margherita":                     "Pizza Margherita 🍕",
	"sushi-sashimi-combo":                  "Sushi & Sashimi Combo 🍣",
	"tacos-al-pastor":                      "Tacos al Pastor 🌮",
	"pad-thai":                             "Pad Thai 🍜",
	"butter-chicken":                       "Butter Chicken 🍛",
	"cheeseburger-and-fries":               "Cheeseburger & Fries 🍔🍟",
	"spaghetti-carbonara":                  "Spaghetti Carbonara 🍝",
	"ramen-tonkotsu":                       "Tonkotsu Ramen 🍜",
	"paella-valenciana":                    "Paella Valenciana 🥘",
	"croissant-au-beurre":                  "Croissant au Beurre 🥐",
	"pho-bo":                               "Phở Bò 🍲",
	"dim-sum-platter":                      "Dim Sum Platter 🥟",
	"falafel-wrap":                         "Falafel Wrap 🥙",
	"moussaka":                             "Moussaka 🍆",
	"bibimbap":                             "Bibimbap 🍚",
	"ceviche-peruano":                      "Ceviche Peruano 🐟",
	"beef-wellington":                      "Beef Wellington 🥩",
	"samosa-chaat":                         "Samosa Chaat 🌶️",
	"fajitas-de-pollo":                     "Fajitas de Pollo 🍗",
	"gyoza":                                "Gyoza 🥟",
	"risotto-ai-funghi":                    "Risotto ai Funghi 🍄",
	"tom-yum-goong":                        "Tom Yum Goong 🌶️🦐",
	"coq-au-vin":                           "Coq au Vin 🍷",
	"churros-con-chocolate":                "Churros con Chocolate 🍫",
	"hot-and-sour-soup":                    "Hot and Sour Soup 🥣",
	"bbq-ribs":                             "BBQ Ribs 🍖",
	"kimchi-jjigae":                        "Kimchi Jjigae 🌶️🍲",
	"lobster-thermidor":                    "Lobster Thermidor 🦞",
	"tiramisu":                             "Tiramisù 🍰",
	"unagi-don":                            "Unagi Don (Eel Rice Bowl) 🍱",
	"chiles-rellenos":                      "Chiles Rellenos 🌶️🧀",
	"green-curry-chicken":                  "Green Curry Chicken 🍛",
	"biryani-hyderabadi":                   "Hyderabadi Biryani 🍚",
	"french-onion-soup":                    "French Onion Soup 🧅",
	"gazpacho":                             "Gazpacho 🍅",
	"kung-pao-chicken":                     "Kung Pao Chicken 🌶️🐔",
	"mac-and-cheese":                       "Macaroni and Cheese 🧀",
	"katsu-curry":                          "Katsu Curry 🍛",
	"baklava":                              "Baklava 🍯",
	"banh-mi":                              "Bánh Mì 🥖",
	"gnocchi-al-pesto":                     "Gnocchi al Pesto 💚",
	"bulgogi":                              "Bulgogi (Korean BBQ Beef) 🥩",
	"shakshuka":                            "Shakshuka 🍳",
	"poutine":                              "Poutine 🍟",
	"escargots-de-bourgogne":               "Escargots de Bourgogne 🐌",
	"tandoori-chicken":                     "Tandoori Chicken 🍗",
	"sushi-california-roll":                "California Roll 🍣",
	"mole-poblano":                         "Mole Poblano 🍫🌶️",
	"massaman-curry":                       "Massaman Curry 🍛",
	"peking-duck":                          "Peking Duck 🦆",
	"fish-and-chips":                       "Fish and Chips 🐟🍟",
	"lasagna-al-forno":                     "Lasagna al Forno 🍝",
	"tempura-shrimp":                       "Shrimp Tempura 🍤",
	"ratatouille":                          "Ratatouille 🍆🍅",
	"tortilla-espanola":                    "Tortilla Española 🥔",
	"hummus-with-pita":                     "Hummus with Pita Bread 🥙",
	"creme-brulee":                         "Crème Brûlée 🔥",
	"sauerbraten":                          "Sauerbraten 🇩🇪",
	"feijoada":                             "Feijoada 🇧🇷",
	"jambalaya":                            "Jambalaya 🌶️🦐",
	"eggplant-parmesan":                    "Eggplant Parmesan 🍆",
	"mapo-tofu":                            "Mapo Tofu 🌶️",
	"chicken-korma":                        "Chicken Korma 🍛",
	"okonomiyaki":                          "Okonomiyaki 🥞",
	"pozole-rojo":                          "Pozole Rojo 🥣",
	"som-tum-thai-green-papaya-salad":      "Som Tum (Green Papaya Salad) 🥗",
	"galbi-korean-bbq-short-ribs":          "Galbi (Korean BBQ Short Ribs) 🍖",
	"bouillabaisse":                        "Bouillabaisse 🐟🥣",
	"patatas-bravas":                       "Patatas Bravas 🥔",
	"chicken-and-waffles":                  "Chicken and Waffles 🍗🧇",
	"fettuccine-alfredo":                   "Fettuccine Alfredo 🍝",
	"yakitori-platter":                     "Yakitori Platter 🍢",
	"enchiladas-verdes":                    "Enchiladas Verdes 🌶️",
	"dosa-with-sambar":                     "Dosa with Sambar 🥞",
	"xiao-long-bao-soup-dumplings":         "Xiao Long Bao (Soup Dumplings) 🥟",
	"vietnamese-spring-rolls":              "Vietnamese Spring Rolls 🦐",
	"shepherds-pie":                        "Shepherd's Pie 🥧",
	"japchae-korean-glass-noodle-stir-fry": "Japchae (Korean Glass Noodle Stir Fry) 🍜",
	"arepas":                               "Arepas 🇻🇪",
	"wiener-schnitzel":                     "Wiener Schnitzel 🇦🇹",
	"osso-buco":                            "Osso Buco 🍖",
	"takoyaki":                             "Takoyaki (Octopus Balls) 🐙",
	"cochinita-pibil":                      "Cochinita Pibil 🐷",
	"palak-paneer":                         "Palak Paneer 🧀",
	"char-siu-chinese-bbq-pork":            "Char Siu (Chinese BBQ Pork) 🍖",
	"bruschetta":                           "Bruschetta 🍅",
	"gambas-al-ajillo":                     "Gambas al Ajillo (Garlic Shrimp) 🦐",
	"clam-chowder-in-a-bread-bowl":         "Clam Chowder in a Bread Bowl 🥣",
	"beef-pho":                             "Beef Pho 🍜",
	"caprese-salad":                        "Caprese Salad 🍅🧀",
	"empanadas-saltenas":                   "Empanadas Salteñas 🥟",
	"blt-sandwich":                         "BLT Sandwich 🥪",
	"korean-fried-chicken":                 "Korean Fried Chicken 🍗",
	"duck-confit":                          "Duck Confit 🦆",
	"aloo-gobi":                            "Aloo Gobi 🥔",
	"bratwurst-with-sauerkraut":            "Bratwurst with Sauerkraut 🇩🇪",
	"picanha":                              "Picanha 🇧🇷",
	"lobster-roll":                         "Lobster Roll 🦞",
	"crab-cakes":                           "Crab Cakes 🦀",
	"key-lime-pie":                         "Key Lime Pie 🥧",
}
